ddressSanitizer:DEADLYSIGNAL
=================================================================
==63949==ERROR: AddressSanitizer: SEGV on unknown address 0x000106ee5080 (pc 0x00010a40eb71 bp 0x70000769eb30 sp 0x70000769e8e0 T2)
==63949==The signal is caused by a READ memory access.
    #0 0x10a40eb70 in SnakeUI::operator=(SnakeUI&) Snake.cpp:191
    #1 0x10a40e758 in SnakeUI::SnakeUI(SnakeUI&) Snake.cpp:182
    #2 0x10a2f63d5 in KNW::DataTCP::CallbackType<SnakeUI>::operator()(void*) DataTCP.hpp:70
    #3 0x10a25f79e in KNW::DataTCP::sendDataToCallback(unsigned short, void*) DataTCP.cpp:19
    #4 0x10a2629d1 in KNW::IOTCP::handleReadData(unsigned short, boost::system::error_code const&, unsigned long) IOTCP.cpp:74
    #5 0x10a26f6fb in KNW::IOTCP::readSocketData(unsigned short)::$_1::operator()(boost::system::error_code, unsigned long) const IOTCP.cpp:60
    #6 0x10a26ee23 in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>::operator()(boost::system::error_code const&, unsigned long, int) read.hpp:285
    #7 0x10a2719b7 in boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long>::operator()() bind_handler.hpp:164
    #8 0x10a271944 in void boost::asio::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long>&, ...) handler_invoke_hook.hpp:69
    #9 0x10a271926 in void boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long>, KNW::IOTCP::readSocketData(unsigned short)::$_1>(boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long>&, KNW::IOTCP::readSocketData(unsigned short)::$_1&) handler_invoke_helpers.hpp:37
    #10 0x10a2718f0 in void boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long>, boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>(boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long>&, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>*) read.hpp:338
    #11 0x10a2718c4 in void boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long>, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1> >(boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long>&, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>&) handler_invoke_helpers.hpp:37
    #12 0x10a2715e0 in void boost::asio::detail::handler_work<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::asio::system_executor>::complete<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>, boost::system::error_code, unsigned long>&, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1>&) handler_work.hpp:82
    #13 0x10a270ea1 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, KNW::IOTCP::readSocketData(unsigned short)::$_1> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) reactive_socket_recv_op.hpp:122
    #14 0x10a221e12 in boost::asio::detail::scheduler_operation::complete(void*, boost::system::error_code const&, unsigned long) scheduler_operation.hpp:40
    #15 0x10a22026f in boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) scheduler.ipp:401
    #16 0x10a21f80c in boost::asio::detail::scheduler::run(boost::system::error_code&) scheduler.ipp:154
    #17 0x10a2165b5 in boost::asio::io_context::run() io_context.ipp:62
    #18 0x10a216300 in IOManager::IORunner() IOManager.cpp:14
    #19 0x10a231643 in boost::_mfi::mf0<void, IOManager>::operator()(IOManager*) const mem_fn_template.hpp:49
    #20 0x10a23150f in void boost::_bi::list1<boost::_bi::value<IOManager*> >::operator()<boost::_mfi::mf0<void, IOManager>, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf0<void, IOManager>&, boost::_bi::list0&, int) bind.hpp:259
    #21 0x10a231416 in boost::_bi::bind_t<void, boost::_mfi::mf0<void, IOManager>, boost::_bi::list1<boost::_bi::value<IOManager*> > >::operator()() bind.hpp:1294
    #22 0x10a2304cb in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, IOManager>, boost::_bi::list1<boost::_bi::value<IOManager*> > > >::run() thread.hpp:117
    #23 0x10ab252c7 in boost::(anonymous namespace)::thread_proxy(void*) (libboost_thread-mt.dylib:x86_64+0x22c7)
    #24 0x7fff796f4304 in _pthread_body (libsystem_pthread.dylib:x86_64+0x3304)
    #25 0x7fff796f726e in _pthread_start (libsystem_pthread.dylib:x86_64+0x626e)
    #26 0x7fff796f3414 in thread_start (libsystem_pthread.dylib:x86_64+0x2414)

==63949==Register values:
rax = 0x0000100000000000  rbx = 0x000070000769eca0  rcx = 0x0000000106ee5080  rdx = 0x0000000106ee5080
rdi = 0x000070000769ebc0  rsi = 0x0000100020ddca10  rbp = 0x000070000769eb30  rsp = 0x000070000769e8e0
 r8 = 0x000061900011fda8   r9 = 0x00006080000815c0  r10 = 0x000061900011fda8  r11 = 0x00007fffac2dbf70
r12 = 0x000070000769f4d0  r13 = 0x00001e0000ed3e9a  r14 = 0x000070000769f4b0  r15 = 0x0000000000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV Snake.cpp:191 in SnakeUI::operator=(SnakeUI&)
Thread T2 created by T0 here:
    #0 0x10ad2141d in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4f41d)
    #1 0x10ab251ed in boost::thread::start_thread_noexcept() (libboost_thread-mt.dylib:x86_64+0x21ed)
    #2 0x10a22f682 in boost::thread::start_thread() thread.hpp:179
    #3 0x10a22f3e9 in boost::thread::thread<boost::_bi::bind_t<void, boost::_mfi::mf0<void, IOManager>, boost::_bi::list1<boost::_bi::value<IOManager*> > >&>(boost::_bi::bind_t<void, boost::_mfi::mf0<void, IOManager>, boost::_bi::list1<boost::_bi::value<IOManager*> > >&&&) thread.hpp:266
    #4 0x10a22d81c in boost::thread::thread<boost::_bi::bind_t<void, boost::_mfi::mf0<void, IOManager>, boost::_bi::list1<boost::_bi::value<IOManager*> > >&>(boost::_bi::bind_t<void, boost::_mfi::mf0<void, IOManager>, boost::_bi::list1<boost::_bi::value<IOManager*> > >&&&) thread.hpp:265
    #5 0x10a215beb in boost::thread* boost::thread_group::create_thread<boost::_bi::bind_t<void, boost::_mfi::mf0<void, IOManager>, boost::_bi::list1<boost::_bi::value<IOManager*> > > >(boost::_bi::bind_t<void, boost::_mfi::mf0<void, IOManager>, boost::_bi::list1<boost::_bi::value<IOManager*> > >) thread_group.hpp:79
    #6 0x10a21573a in IOManager::IOManager(unsigned long) IOManager.cpp:9
    #7 0x10a21638c in IOManager::IOManager(unsigned long) IOManager.cpp:6
    #8 0x10a13cf02 in Univers::Univers() memory:3078
    #9 0x10a13eab4 in Univers::Univers() Univers.cpp:53
    #10 0x10a03f0b4 in main main.cpp:76
    #11 0x7fff79500ed8 in start (libdyld.dylib:x86_64+0x16ed8)

==63949==ABORTING
[1]    63949 abort      ./nibbler
