# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ntoniolo/nibbler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ntoniolo/nibbler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ntoniolo/nibbler/CMakeFiles /Users/ntoniolo/nibbler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ntoniolo/nibbler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nibbler

# Build rule for target.
nibbler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nibbler
.PHONY : nibbler

# fast build rule for target.
nibbler/fast:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/build
.PHONY : nibbler/fast

class/KNU/World.o: class/KNU/World.cpp.o

.PHONY : class/KNU/World.o

# target to build an object file
class/KNU/World.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/World.cpp.o
.PHONY : class/KNU/World.cpp.o

class/KNU/World.i: class/KNU/World.cpp.i

.PHONY : class/KNU/World.i

# target to preprocess a source file
class/KNU/World.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/World.cpp.i
.PHONY : class/KNU/World.cpp.i

class/KNU/World.s: class/KNU/World.cpp.s

.PHONY : class/KNU/World.s

# target to generate assembly for a file
class/KNU/World.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/World.cpp.s
.PHONY : class/KNU/World.cpp.s

class/KNU/component/Component.o: class/KNU/component/Component.cpp.o

.PHONY : class/KNU/component/Component.o

# target to build an object file
class/KNU/component/Component.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/component/Component.cpp.o
.PHONY : class/KNU/component/Component.cpp.o

class/KNU/component/Component.i: class/KNU/component/Component.cpp.i

.PHONY : class/KNU/component/Component.i

# target to preprocess a source file
class/KNU/component/Component.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/component/Component.cpp.i
.PHONY : class/KNU/component/Component.cpp.i

class/KNU/component/Component.s: class/KNU/component/Component.cpp.s

.PHONY : class/KNU/component/Component.s

# target to generate assembly for a file
class/KNU/component/Component.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/component/Component.cpp.s
.PHONY : class/KNU/component/Component.cpp.s

class/KNU/entities/Entity.o: class/KNU/entities/Entity.cpp.o

.PHONY : class/KNU/entities/Entity.o

# target to build an object file
class/KNU/entities/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/entities/Entity.cpp.o
.PHONY : class/KNU/entities/Entity.cpp.o

class/KNU/entities/Entity.i: class/KNU/entities/Entity.cpp.i

.PHONY : class/KNU/entities/Entity.i

# target to preprocess a source file
class/KNU/entities/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/entities/Entity.cpp.i
.PHONY : class/KNU/entities/Entity.cpp.i

class/KNU/entities/Entity.s: class/KNU/entities/Entity.cpp.s

.PHONY : class/KNU/entities/Entity.s

# target to generate assembly for a file
class/KNU/entities/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/entities/Entity.cpp.s
.PHONY : class/KNU/entities/Entity.cpp.s

class/KNU/events/EventManager.o: class/KNU/events/EventManager.cpp.o

.PHONY : class/KNU/events/EventManager.o

# target to build an object file
class/KNU/events/EventManager.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/events/EventManager.cpp.o
.PHONY : class/KNU/events/EventManager.cpp.o

class/KNU/events/EventManager.i: class/KNU/events/EventManager.cpp.i

.PHONY : class/KNU/events/EventManager.i

# target to preprocess a source file
class/KNU/events/EventManager.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/events/EventManager.cpp.i
.PHONY : class/KNU/events/EventManager.cpp.i

class/KNU/events/EventManager.s: class/KNU/events/EventManager.cpp.s

.PHONY : class/KNU/events/EventManager.s

# target to generate assembly for a file
class/KNU/events/EventManager.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/events/EventManager.cpp.s
.PHONY : class/KNU/events/EventManager.cpp.s

class/KNU/systems/System.o: class/KNU/systems/System.cpp.o

.PHONY : class/KNU/systems/System.o

# target to build an object file
class/KNU/systems/System.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/systems/System.cpp.o
.PHONY : class/KNU/systems/System.cpp.o

class/KNU/systems/System.i: class/KNU/systems/System.cpp.i

.PHONY : class/KNU/systems/System.i

# target to preprocess a source file
class/KNU/systems/System.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/systems/System.cpp.i
.PHONY : class/KNU/systems/System.cpp.i

class/KNU/systems/System.s: class/KNU/systems/System.cpp.s

.PHONY : class/KNU/systems/System.s

# target to generate assembly for a file
class/KNU/systems/System.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/systems/System.cpp.s
.PHONY : class/KNU/systems/System.cpp.s

class/KNU/utils/Signature.o: class/KNU/utils/Signature.cpp.o

.PHONY : class/KNU/utils/Signature.o

# target to build an object file
class/KNU/utils/Signature.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/utils/Signature.cpp.o
.PHONY : class/KNU/utils/Signature.cpp.o

class/KNU/utils/Signature.i: class/KNU/utils/Signature.cpp.i

.PHONY : class/KNU/utils/Signature.i

# target to preprocess a source file
class/KNU/utils/Signature.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/utils/Signature.cpp.i
.PHONY : class/KNU/utils/Signature.cpp.i

class/KNU/utils/Signature.s: class/KNU/utils/Signature.cpp.s

.PHONY : class/KNU/utils/Signature.s

# target to generate assembly for a file
class/KNU/utils/Signature.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/KNU/utils/Signature.cpp.s
.PHONY : class/KNU/utils/Signature.cpp.s

class/Univers.o: class/Univers.cpp.o

.PHONY : class/Univers.o

# target to build an object file
class/Univers.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/Univers.cpp.o
.PHONY : class/Univers.cpp.o

class/Univers.i: class/Univers.cpp.i

.PHONY : class/Univers.i

# target to preprocess a source file
class/Univers.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/Univers.cpp.i
.PHONY : class/Univers.cpp.i

class/Univers.s: class/Univers.cpp.s

.PHONY : class/Univers.s

# target to generate assembly for a file
class/Univers.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/Univers.cpp.s
.PHONY : class/Univers.cpp.s

class/component/CollisionComponent.o: class/component/CollisionComponent.cpp.o

.PHONY : class/component/CollisionComponent.o

# target to build an object file
class/component/CollisionComponent.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/CollisionComponent.cpp.o
.PHONY : class/component/CollisionComponent.cpp.o

class/component/CollisionComponent.i: class/component/CollisionComponent.cpp.i

.PHONY : class/component/CollisionComponent.i

# target to preprocess a source file
class/component/CollisionComponent.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/CollisionComponent.cpp.i
.PHONY : class/component/CollisionComponent.cpp.i

class/component/CollisionComponent.s: class/component/CollisionComponent.cpp.s

.PHONY : class/component/CollisionComponent.s

# target to generate assembly for a file
class/component/CollisionComponent.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/CollisionComponent.cpp.s
.PHONY : class/component/CollisionComponent.cpp.s

class/component/FollowComponent.o: class/component/FollowComponent.cpp.o

.PHONY : class/component/FollowComponent.o

# target to build an object file
class/component/FollowComponent.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/FollowComponent.cpp.o
.PHONY : class/component/FollowComponent.cpp.o

class/component/FollowComponent.i: class/component/FollowComponent.cpp.i

.PHONY : class/component/FollowComponent.i

# target to preprocess a source file
class/component/FollowComponent.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/FollowComponent.cpp.i
.PHONY : class/component/FollowComponent.cpp.i

class/component/FollowComponent.s: class/component/FollowComponent.cpp.s

.PHONY : class/component/FollowComponent.s

# target to generate assembly for a file
class/component/FollowComponent.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/FollowComponent.cpp.s
.PHONY : class/component/FollowComponent.cpp.s

class/component/JoystickComponent.o: class/component/JoystickComponent.cpp.o

.PHONY : class/component/JoystickComponent.o

# target to build an object file
class/component/JoystickComponent.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/JoystickComponent.cpp.o
.PHONY : class/component/JoystickComponent.cpp.o

class/component/JoystickComponent.i: class/component/JoystickComponent.cpp.i

.PHONY : class/component/JoystickComponent.i

# target to preprocess a source file
class/component/JoystickComponent.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/JoystickComponent.cpp.i
.PHONY : class/component/JoystickComponent.cpp.i

class/component/JoystickComponent.s: class/component/JoystickComponent.cpp.s

.PHONY : class/component/JoystickComponent.s

# target to generate assembly for a file
class/component/JoystickComponent.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/JoystickComponent.cpp.s
.PHONY : class/component/JoystickComponent.cpp.s

class/component/MotionComponent.o: class/component/MotionComponent.cpp.o

.PHONY : class/component/MotionComponent.o

# target to build an object file
class/component/MotionComponent.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/MotionComponent.cpp.o
.PHONY : class/component/MotionComponent.cpp.o

class/component/MotionComponent.i: class/component/MotionComponent.cpp.i

.PHONY : class/component/MotionComponent.i

# target to preprocess a source file
class/component/MotionComponent.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/MotionComponent.cpp.i
.PHONY : class/component/MotionComponent.cpp.i

class/component/MotionComponent.s: class/component/MotionComponent.cpp.s

.PHONY : class/component/MotionComponent.s

# target to generate assembly for a file
class/component/MotionComponent.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/MotionComponent.cpp.s
.PHONY : class/component/MotionComponent.cpp.s

class/component/PositionComponent.o: class/component/PositionComponent.cpp.o

.PHONY : class/component/PositionComponent.o

# target to build an object file
class/component/PositionComponent.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/PositionComponent.cpp.o
.PHONY : class/component/PositionComponent.cpp.o

class/component/PositionComponent.i: class/component/PositionComponent.cpp.i

.PHONY : class/component/PositionComponent.i

# target to preprocess a source file
class/component/PositionComponent.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/PositionComponent.cpp.i
.PHONY : class/component/PositionComponent.cpp.i

class/component/PositionComponent.s: class/component/PositionComponent.cpp.s

.PHONY : class/component/PositionComponent.s

# target to generate assembly for a file
class/component/PositionComponent.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/PositionComponent.cpp.s
.PHONY : class/component/PositionComponent.cpp.s

class/component/SpriteComponent.o: class/component/SpriteComponent.cpp.o

.PHONY : class/component/SpriteComponent.o

# target to build an object file
class/component/SpriteComponent.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/SpriteComponent.cpp.o
.PHONY : class/component/SpriteComponent.cpp.o

class/component/SpriteComponent.i: class/component/SpriteComponent.cpp.i

.PHONY : class/component/SpriteComponent.i

# target to preprocess a source file
class/component/SpriteComponent.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/SpriteComponent.cpp.i
.PHONY : class/component/SpriteComponent.cpp.i

class/component/SpriteComponent.s: class/component/SpriteComponent.cpp.s

.PHONY : class/component/SpriteComponent.s

# target to generate assembly for a file
class/component/SpriteComponent.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/component/SpriteComponent.cpp.s
.PHONY : class/component/SpriteComponent.cpp.s

class/cores/main.o: class/cores/main.cpp.o

.PHONY : class/cores/main.o

# target to build an object file
class/cores/main.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/cores/main.cpp.o
.PHONY : class/cores/main.cpp.o

class/cores/main.i: class/cores/main.cpp.i

.PHONY : class/cores/main.i

# target to preprocess a source file
class/cores/main.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/cores/main.cpp.i
.PHONY : class/cores/main.cpp.i

class/cores/main.s: class/cores/main.cpp.s

.PHONY : class/cores/main.s

# target to generate assembly for a file
class/cores/main.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/cores/main.cpp.s
.PHONY : class/cores/main.cpp.s

class/events/FoodEvent.o: class/events/FoodEvent.cpp.o

.PHONY : class/events/FoodEvent.o

# target to build an object file
class/events/FoodEvent.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/events/FoodEvent.cpp.o
.PHONY : class/events/FoodEvent.cpp.o

class/events/FoodEvent.i: class/events/FoodEvent.cpp.i

.PHONY : class/events/FoodEvent.i

# target to preprocess a source file
class/events/FoodEvent.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/events/FoodEvent.cpp.i
.PHONY : class/events/FoodEvent.cpp.i

class/events/FoodEvent.s: class/events/FoodEvent.cpp.s

.PHONY : class/events/FoodEvent.s

# target to generate assembly for a file
class/events/FoodEvent.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/events/FoodEvent.cpp.s
.PHONY : class/events/FoodEvent.cpp.s

class/events/JoystickEvent.o: class/events/JoystickEvent.cpp.o

.PHONY : class/events/JoystickEvent.o

# target to build an object file
class/events/JoystickEvent.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/events/JoystickEvent.cpp.o
.PHONY : class/events/JoystickEvent.cpp.o

class/events/JoystickEvent.i: class/events/JoystickEvent.cpp.i

.PHONY : class/events/JoystickEvent.i

# target to preprocess a source file
class/events/JoystickEvent.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/events/JoystickEvent.cpp.i
.PHONY : class/events/JoystickEvent.cpp.i

class/events/JoystickEvent.s: class/events/JoystickEvent.cpp.s

.PHONY : class/events/JoystickEvent.s

# target to generate assembly for a file
class/events/JoystickEvent.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/events/JoystickEvent.cpp.s
.PHONY : class/events/JoystickEvent.cpp.s

class/factory/Factory.o: class/factory/Factory.cpp.o

.PHONY : class/factory/Factory.o

# target to build an object file
class/factory/Factory.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/factory/Factory.cpp.o
.PHONY : class/factory/Factory.cpp.o

class/factory/Factory.i: class/factory/Factory.cpp.i

.PHONY : class/factory/Factory.i

# target to preprocess a source file
class/factory/Factory.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/factory/Factory.cpp.i
.PHONY : class/factory/Factory.cpp.i

class/factory/Factory.s: class/factory/Factory.cpp.s

.PHONY : class/factory/Factory.s

# target to generate assembly for a file
class/factory/Factory.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/factory/Factory.cpp.s
.PHONY : class/factory/Factory.cpp.s

class/gui/Core.o: class/gui/Core.cpp.o

.PHONY : class/gui/Core.o

# target to build an object file
class/gui/Core.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/Core.cpp.o
.PHONY : class/gui/Core.cpp.o

class/gui/Core.i: class/gui/Core.cpp.i

.PHONY : class/gui/Core.i

# target to preprocess a source file
class/gui/Core.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/Core.cpp.i
.PHONY : class/gui/Core.cpp.i

class/gui/Core.s: class/gui/Core.cpp.s

.PHONY : class/gui/Core.s

# target to generate assembly for a file
class/gui/Core.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/Core.cpp.s
.PHONY : class/gui/Core.cpp.s

class/gui/imgui_demo.o: class/gui/imgui_demo.cpp.o

.PHONY : class/gui/imgui_demo.o

# target to build an object file
class/gui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/imgui_demo.cpp.o
.PHONY : class/gui/imgui_demo.cpp.o

class/gui/imgui_demo.i: class/gui/imgui_demo.cpp.i

.PHONY : class/gui/imgui_demo.i

# target to preprocess a source file
class/gui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/imgui_demo.cpp.i
.PHONY : class/gui/imgui_demo.cpp.i

class/gui/imgui_demo.s: class/gui/imgui_demo.cpp.s

.PHONY : class/gui/imgui_demo.s

# target to generate assembly for a file
class/gui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/imgui_demo.cpp.s
.PHONY : class/gui/imgui_demo.cpp.s

class/gui/widget/AWidget.o: class/gui/widget/AWidget.cpp.o

.PHONY : class/gui/widget/AWidget.o

# target to build an object file
class/gui/widget/AWidget.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/AWidget.cpp.o
.PHONY : class/gui/widget/AWidget.cpp.o

class/gui/widget/AWidget.i: class/gui/widget/AWidget.cpp.i

.PHONY : class/gui/widget/AWidget.i

# target to preprocess a source file
class/gui/widget/AWidget.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/AWidget.cpp.i
.PHONY : class/gui/widget/AWidget.cpp.i

class/gui/widget/AWidget.s: class/gui/widget/AWidget.cpp.s

.PHONY : class/gui/widget/AWidget.s

# target to generate assembly for a file
class/gui/widget/AWidget.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/AWidget.cpp.s
.PHONY : class/gui/widget/AWidget.cpp.s

class/gui/widget/WidgetChat.o: class/gui/widget/WidgetChat.cpp.o

.PHONY : class/gui/widget/WidgetChat.o

# target to build an object file
class/gui/widget/WidgetChat.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetChat.cpp.o
.PHONY : class/gui/widget/WidgetChat.cpp.o

class/gui/widget/WidgetChat.i: class/gui/widget/WidgetChat.cpp.i

.PHONY : class/gui/widget/WidgetChat.i

# target to preprocess a source file
class/gui/widget/WidgetChat.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetChat.cpp.i
.PHONY : class/gui/widget/WidgetChat.cpp.i

class/gui/widget/WidgetChat.s: class/gui/widget/WidgetChat.cpp.s

.PHONY : class/gui/widget/WidgetChat.s

# target to generate assembly for a file
class/gui/widget/WidgetChat.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetChat.cpp.s
.PHONY : class/gui/widget/WidgetChat.cpp.s

class/gui/widget/WidgetExit.o: class/gui/widget/WidgetExit.cpp.o

.PHONY : class/gui/widget/WidgetExit.o

# target to build an object file
class/gui/widget/WidgetExit.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetExit.cpp.o
.PHONY : class/gui/widget/WidgetExit.cpp.o

class/gui/widget/WidgetExit.i: class/gui/widget/WidgetExit.cpp.i

.PHONY : class/gui/widget/WidgetExit.i

# target to preprocess a source file
class/gui/widget/WidgetExit.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetExit.cpp.i
.PHONY : class/gui/widget/WidgetExit.cpp.i

class/gui/widget/WidgetExit.s: class/gui/widget/WidgetExit.cpp.s

.PHONY : class/gui/widget/WidgetExit.s

# target to generate assembly for a file
class/gui/widget/WidgetExit.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetExit.cpp.s
.PHONY : class/gui/widget/WidgetExit.cpp.s

class/gui/widget/WidgetLobby.o: class/gui/widget/WidgetLobby.cpp.o

.PHONY : class/gui/widget/WidgetLobby.o

# target to build an object file
class/gui/widget/WidgetLobby.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetLobby.cpp.o
.PHONY : class/gui/widget/WidgetLobby.cpp.o

class/gui/widget/WidgetLobby.i: class/gui/widget/WidgetLobby.cpp.i

.PHONY : class/gui/widget/WidgetLobby.i

# target to preprocess a source file
class/gui/widget/WidgetLobby.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetLobby.cpp.i
.PHONY : class/gui/widget/WidgetLobby.cpp.i

class/gui/widget/WidgetLobby.s: class/gui/widget/WidgetLobby.cpp.s

.PHONY : class/gui/widget/WidgetLobby.s

# target to generate assembly for a file
class/gui/widget/WidgetLobby.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetLobby.cpp.s
.PHONY : class/gui/widget/WidgetLobby.cpp.s

class/gui/widget/WidgetSnake.o: class/gui/widget/WidgetSnake.cpp.o

.PHONY : class/gui/widget/WidgetSnake.o

# target to build an object file
class/gui/widget/WidgetSnake.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetSnake.cpp.o
.PHONY : class/gui/widget/WidgetSnake.cpp.o

class/gui/widget/WidgetSnake.i: class/gui/widget/WidgetSnake.cpp.i

.PHONY : class/gui/widget/WidgetSnake.i

# target to preprocess a source file
class/gui/widget/WidgetSnake.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetSnake.cpp.i
.PHONY : class/gui/widget/WidgetSnake.cpp.i

class/gui/widget/WidgetSnake.s: class/gui/widget/WidgetSnake.cpp.s

.PHONY : class/gui/widget/WidgetSnake.s

# target to generate assembly for a file
class/gui/widget/WidgetSnake.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/gui/widget/WidgetSnake.cpp.s
.PHONY : class/gui/widget/WidgetSnake.cpp.s

class/logger/display/logger_debug.o: class/logger/display/logger_debug.cpp.o

.PHONY : class/logger/display/logger_debug.o

# target to build an object file
class/logger/display/logger_debug.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_debug.cpp.o
.PHONY : class/logger/display/logger_debug.cpp.o

class/logger/display/logger_debug.i: class/logger/display/logger_debug.cpp.i

.PHONY : class/logger/display/logger_debug.i

# target to preprocess a source file
class/logger/display/logger_debug.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_debug.cpp.i
.PHONY : class/logger/display/logger_debug.cpp.i

class/logger/display/logger_debug.s: class/logger/display/logger_debug.cpp.s

.PHONY : class/logger/display/logger_debug.s

# target to generate assembly for a file
class/logger/display/logger_debug.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_debug.cpp.s
.PHONY : class/logger/display/logger_debug.cpp.s

class/logger/display/logger_error.o: class/logger/display/logger_error.cpp.o

.PHONY : class/logger/display/logger_error.o

# target to build an object file
class/logger/display/logger_error.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_error.cpp.o
.PHONY : class/logger/display/logger_error.cpp.o

class/logger/display/logger_error.i: class/logger/display/logger_error.cpp.i

.PHONY : class/logger/display/logger_error.i

# target to preprocess a source file
class/logger/display/logger_error.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_error.cpp.i
.PHONY : class/logger/display/logger_error.cpp.i

class/logger/display/logger_error.s: class/logger/display/logger_error.cpp.s

.PHONY : class/logger/display/logger_error.s

# target to generate assembly for a file
class/logger/display/logger_error.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_error.cpp.s
.PHONY : class/logger/display/logger_error.cpp.s

class/logger/display/logger_fatal.o: class/logger/display/logger_fatal.cpp.o

.PHONY : class/logger/display/logger_fatal.o

# target to build an object file
class/logger/display/logger_fatal.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_fatal.cpp.o
.PHONY : class/logger/display/logger_fatal.cpp.o

class/logger/display/logger_fatal.i: class/logger/display/logger_fatal.cpp.i

.PHONY : class/logger/display/logger_fatal.i

# target to preprocess a source file
class/logger/display/logger_fatal.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_fatal.cpp.i
.PHONY : class/logger/display/logger_fatal.cpp.i

class/logger/display/logger_fatal.s: class/logger/display/logger_fatal.cpp.s

.PHONY : class/logger/display/logger_fatal.s

# target to generate assembly for a file
class/logger/display/logger_fatal.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_fatal.cpp.s
.PHONY : class/logger/display/logger_fatal.cpp.s

class/logger/display/logger_info.o: class/logger/display/logger_info.cpp.o

.PHONY : class/logger/display/logger_info.o

# target to build an object file
class/logger/display/logger_info.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_info.cpp.o
.PHONY : class/logger/display/logger_info.cpp.o

class/logger/display/logger_info.i: class/logger/display/logger_info.cpp.i

.PHONY : class/logger/display/logger_info.i

# target to preprocess a source file
class/logger/display/logger_info.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_info.cpp.i
.PHONY : class/logger/display/logger_info.cpp.i

class/logger/display/logger_info.s: class/logger/display/logger_info.cpp.s

.PHONY : class/logger/display/logger_info.s

# target to generate assembly for a file
class/logger/display/logger_info.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_info.cpp.s
.PHONY : class/logger/display/logger_info.cpp.s

class/logger/display/logger_success.o: class/logger/display/logger_success.cpp.o

.PHONY : class/logger/display/logger_success.o

# target to build an object file
class/logger/display/logger_success.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_success.cpp.o
.PHONY : class/logger/display/logger_success.cpp.o

class/logger/display/logger_success.i: class/logger/display/logger_success.cpp.i

.PHONY : class/logger/display/logger_success.i

# target to preprocess a source file
class/logger/display/logger_success.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_success.cpp.i
.PHONY : class/logger/display/logger_success.cpp.i

class/logger/display/logger_success.s: class/logger/display/logger_success.cpp.s

.PHONY : class/logger/display/logger_success.s

# target to generate assembly for a file
class/logger/display/logger_success.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_success.cpp.s
.PHONY : class/logger/display/logger_success.cpp.s

class/logger/display/logger_trace.o: class/logger/display/logger_trace.cpp.o

.PHONY : class/logger/display/logger_trace.o

# target to build an object file
class/logger/display/logger_trace.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_trace.cpp.o
.PHONY : class/logger/display/logger_trace.cpp.o

class/logger/display/logger_trace.i: class/logger/display/logger_trace.cpp.i

.PHONY : class/logger/display/logger_trace.i

# target to preprocess a source file
class/logger/display/logger_trace.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_trace.cpp.i
.PHONY : class/logger/display/logger_trace.cpp.i

class/logger/display/logger_trace.s: class/logger/display/logger_trace.cpp.s

.PHONY : class/logger/display/logger_trace.s

# target to generate assembly for a file
class/logger/display/logger_trace.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_trace.cpp.s
.PHONY : class/logger/display/logger_trace.cpp.s

class/logger/display/logger_warn.o: class/logger/display/logger_warn.cpp.o

.PHONY : class/logger/display/logger_warn.o

# target to build an object file
class/logger/display/logger_warn.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_warn.cpp.o
.PHONY : class/logger/display/logger_warn.cpp.o

class/logger/display/logger_warn.i: class/logger/display/logger_warn.cpp.i

.PHONY : class/logger/display/logger_warn.i

# target to preprocess a source file
class/logger/display/logger_warn.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_warn.cpp.i
.PHONY : class/logger/display/logger_warn.cpp.i

class/logger/display/logger_warn.s: class/logger/display/logger_warn.cpp.s

.PHONY : class/logger/display/logger_warn.s

# target to generate assembly for a file
class/logger/display/logger_warn.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/display/logger_warn.cpp.s
.PHONY : class/logger/display/logger_warn.cpp.s

class/logger/logger/logger_init.o: class/logger/logger/logger_init.cpp.o

.PHONY : class/logger/logger/logger_init.o

# target to build an object file
class/logger/logger/logger_init.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/logger/logger_init.cpp.o
.PHONY : class/logger/logger/logger_init.cpp.o

class/logger/logger/logger_init.i: class/logger/logger/logger_init.cpp.i

.PHONY : class/logger/logger/logger_init.i

# target to preprocess a source file
class/logger/logger/logger_init.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/logger/logger_init.cpp.i
.PHONY : class/logger/logger/logger_init.cpp.i

class/logger/logger/logger_init.s: class/logger/logger/logger_init.cpp.s

.PHONY : class/logger/logger/logger_init.s

# target to generate assembly for a file
class/logger/logger/logger_init.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/logger/logger_init.cpp.s
.PHONY : class/logger/logger/logger_init.cpp.s

class/logger/utils/logger_get_time.o: class/logger/utils/logger_get_time.cpp.o

.PHONY : class/logger/utils/logger_get_time.o

# target to build an object file
class/logger/utils/logger_get_time.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/utils/logger_get_time.cpp.o
.PHONY : class/logger/utils/logger_get_time.cpp.o

class/logger/utils/logger_get_time.i: class/logger/utils/logger_get_time.cpp.i

.PHONY : class/logger/utils/logger_get_time.i

# target to preprocess a source file
class/logger/utils/logger_get_time.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/utils/logger_get_time.cpp.i
.PHONY : class/logger/utils/logger_get_time.cpp.i

class/logger/utils/logger_get_time.s: class/logger/utils/logger_get_time.cpp.s

.PHONY : class/logger/utils/logger_get_time.s

# target to generate assembly for a file
class/logger/utils/logger_get_time.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/utils/logger_get_time.cpp.s
.PHONY : class/logger/utils/logger_get_time.cpp.s

class/logger/utils/logger_init_open_file.o: class/logger/utils/logger_init_open_file.cpp.o

.PHONY : class/logger/utils/logger_init_open_file.o

# target to build an object file
class/logger/utils/logger_init_open_file.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/utils/logger_init_open_file.cpp.o
.PHONY : class/logger/utils/logger_init_open_file.cpp.o

class/logger/utils/logger_init_open_file.i: class/logger/utils/logger_init_open_file.cpp.i

.PHONY : class/logger/utils/logger_init_open_file.i

# target to preprocess a source file
class/logger/utils/logger_init_open_file.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/utils/logger_init_open_file.cpp.i
.PHONY : class/logger/utils/logger_init_open_file.cpp.i

class/logger/utils/logger_init_open_file.s: class/logger/utils/logger_init_open_file.cpp.s

.PHONY : class/logger/utils/logger_init_open_file.s

# target to generate assembly for a file
class/logger/utils/logger_init_open_file.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/logger/utils/logger_init_open_file.cpp.s
.PHONY : class/logger/utils/logger_init_open_file.cpp.s

class/network/ClientTCP.o: class/network/ClientTCP.cpp.o

.PHONY : class/network/ClientTCP.o

# target to build an object file
class/network/ClientTCP.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/ClientTCP.cpp.o
.PHONY : class/network/ClientTCP.cpp.o

class/network/ClientTCP.i: class/network/ClientTCP.cpp.i

.PHONY : class/network/ClientTCP.i

# target to preprocess a source file
class/network/ClientTCP.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/ClientTCP.cpp.i
.PHONY : class/network/ClientTCP.cpp.i

class/network/ClientTCP.s: class/network/ClientTCP.cpp.s

.PHONY : class/network/ClientTCP.s

# target to generate assembly for a file
class/network/ClientTCP.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/ClientTCP.cpp.s
.PHONY : class/network/ClientTCP.cpp.s

class/network/Network.o: class/network/Network.cpp.o

.PHONY : class/network/Network.o

# target to build an object file
class/network/Network.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/Network.cpp.o
.PHONY : class/network/Network.cpp.o

class/network/Network.i: class/network/Network.cpp.i

.PHONY : class/network/Network.i

# target to preprocess a source file
class/network/Network.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/Network.cpp.i
.PHONY : class/network/Network.cpp.i

class/network/Network.s: class/network/Network.cpp.s

.PHONY : class/network/Network.s

# target to generate assembly for a file
class/network/Network.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/Network.cpp.s
.PHONY : class/network/Network.cpp.s

class/network/ServerTCP.o: class/network/ServerTCP.cpp.o

.PHONY : class/network/ServerTCP.o

# target to build an object file
class/network/ServerTCP.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/ServerTCP.cpp.o
.PHONY : class/network/ServerTCP.cpp.o

class/network/ServerTCP.i: class/network/ServerTCP.cpp.i

.PHONY : class/network/ServerTCP.i

# target to preprocess a source file
class/network/ServerTCP.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/ServerTCP.cpp.i
.PHONY : class/network/ServerTCP.cpp.i

class/network/ServerTCP.s: class/network/ServerTCP.cpp.s

.PHONY : class/network/ServerTCP.s

# target to generate assembly for a file
class/network/ServerTCP.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/ServerTCP.cpp.s
.PHONY : class/network/ServerTCP.cpp.s

class/network/UtilsTCP.o: class/network/UtilsTCP.cpp.o

.PHONY : class/network/UtilsTCP.o

# target to build an object file
class/network/UtilsTCP.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/UtilsTCP.cpp.o
.PHONY : class/network/UtilsTCP.cpp.o

class/network/UtilsTCP.i: class/network/UtilsTCP.cpp.i

.PHONY : class/network/UtilsTCP.i

# target to preprocess a source file
class/network/UtilsTCP.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/UtilsTCP.cpp.i
.PHONY : class/network/UtilsTCP.cpp.i

class/network/UtilsTCP.s: class/network/UtilsTCP.cpp.s

.PHONY : class/network/UtilsTCP.s

# target to generate assembly for a file
class/network/UtilsTCP.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/network/UtilsTCP.cpp.s
.PHONY : class/network/UtilsTCP.cpp.s

class/systems/CollisionSystem.o: class/systems/CollisionSystem.cpp.o

.PHONY : class/systems/CollisionSystem.o

# target to build an object file
class/systems/CollisionSystem.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/CollisionSystem.cpp.o
.PHONY : class/systems/CollisionSystem.cpp.o

class/systems/CollisionSystem.i: class/systems/CollisionSystem.cpp.i

.PHONY : class/systems/CollisionSystem.i

# target to preprocess a source file
class/systems/CollisionSystem.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/CollisionSystem.cpp.i
.PHONY : class/systems/CollisionSystem.cpp.i

class/systems/CollisionSystem.s: class/systems/CollisionSystem.cpp.s

.PHONY : class/systems/CollisionSystem.s

# target to generate assembly for a file
class/systems/CollisionSystem.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/CollisionSystem.cpp.s
.PHONY : class/systems/CollisionSystem.cpp.s

class/systems/FollowSystem.o: class/systems/FollowSystem.cpp.o

.PHONY : class/systems/FollowSystem.o

# target to build an object file
class/systems/FollowSystem.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/FollowSystem.cpp.o
.PHONY : class/systems/FollowSystem.cpp.o

class/systems/FollowSystem.i: class/systems/FollowSystem.cpp.i

.PHONY : class/systems/FollowSystem.i

# target to preprocess a source file
class/systems/FollowSystem.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/FollowSystem.cpp.i
.PHONY : class/systems/FollowSystem.cpp.i

class/systems/FollowSystem.s: class/systems/FollowSystem.cpp.s

.PHONY : class/systems/FollowSystem.s

# target to generate assembly for a file
class/systems/FollowSystem.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/FollowSystem.cpp.s
.PHONY : class/systems/FollowSystem.cpp.s

class/systems/FoodSystem.o: class/systems/FoodSystem.cpp.o

.PHONY : class/systems/FoodSystem.o

# target to build an object file
class/systems/FoodSystem.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/FoodSystem.cpp.o
.PHONY : class/systems/FoodSystem.cpp.o

class/systems/FoodSystem.i: class/systems/FoodSystem.cpp.i

.PHONY : class/systems/FoodSystem.i

# target to preprocess a source file
class/systems/FoodSystem.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/FoodSystem.cpp.i
.PHONY : class/systems/FoodSystem.cpp.i

class/systems/FoodSystem.s: class/systems/FoodSystem.cpp.s

.PHONY : class/systems/FoodSystem.s

# target to generate assembly for a file
class/systems/FoodSystem.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/FoodSystem.cpp.s
.PHONY : class/systems/FoodSystem.cpp.s

class/systems/JoystickSystem.o: class/systems/JoystickSystem.cpp.o

.PHONY : class/systems/JoystickSystem.o

# target to build an object file
class/systems/JoystickSystem.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/JoystickSystem.cpp.o
.PHONY : class/systems/JoystickSystem.cpp.o

class/systems/JoystickSystem.i: class/systems/JoystickSystem.cpp.i

.PHONY : class/systems/JoystickSystem.i

# target to preprocess a source file
class/systems/JoystickSystem.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/JoystickSystem.cpp.i
.PHONY : class/systems/JoystickSystem.cpp.i

class/systems/JoystickSystem.s: class/systems/JoystickSystem.cpp.s

.PHONY : class/systems/JoystickSystem.s

# target to generate assembly for a file
class/systems/JoystickSystem.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/JoystickSystem.cpp.s
.PHONY : class/systems/JoystickSystem.cpp.s

class/systems/MotionSystem.o: class/systems/MotionSystem.cpp.o

.PHONY : class/systems/MotionSystem.o

# target to build an object file
class/systems/MotionSystem.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/MotionSystem.cpp.o
.PHONY : class/systems/MotionSystem.cpp.o

class/systems/MotionSystem.i: class/systems/MotionSystem.cpp.i

.PHONY : class/systems/MotionSystem.i

# target to preprocess a source file
class/systems/MotionSystem.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/MotionSystem.cpp.i
.PHONY : class/systems/MotionSystem.cpp.i

class/systems/MotionSystem.s: class/systems/MotionSystem.cpp.s

.PHONY : class/systems/MotionSystem.s

# target to generate assembly for a file
class/systems/MotionSystem.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/MotionSystem.cpp.s
.PHONY : class/systems/MotionSystem.cpp.s

class/systems/RenderSystem.o: class/systems/RenderSystem.cpp.o

.PHONY : class/systems/RenderSystem.o

# target to build an object file
class/systems/RenderSystem.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/RenderSystem.cpp.o
.PHONY : class/systems/RenderSystem.cpp.o

class/systems/RenderSystem.i: class/systems/RenderSystem.cpp.i

.PHONY : class/systems/RenderSystem.i

# target to preprocess a source file
class/systems/RenderSystem.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/RenderSystem.cpp.i
.PHONY : class/systems/RenderSystem.cpp.i

class/systems/RenderSystem.s: class/systems/RenderSystem.cpp.s

.PHONY : class/systems/RenderSystem.s

# target to generate assembly for a file
class/systems/RenderSystem.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/class/systems/RenderSystem.cpp.s
.PHONY : class/systems/RenderSystem.cpp.s

imgui-sfml/imgui-SFML.o: imgui-sfml/imgui-SFML.cpp.o

.PHONY : imgui-sfml/imgui-SFML.o

# target to build an object file
imgui-sfml/imgui-SFML.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui-SFML.cpp.o
.PHONY : imgui-sfml/imgui-SFML.cpp.o

imgui-sfml/imgui-SFML.i: imgui-sfml/imgui-SFML.cpp.i

.PHONY : imgui-sfml/imgui-SFML.i

# target to preprocess a source file
imgui-sfml/imgui-SFML.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui-SFML.cpp.i
.PHONY : imgui-sfml/imgui-SFML.cpp.i

imgui-sfml/imgui-SFML.s: imgui-sfml/imgui-SFML.cpp.s

.PHONY : imgui-sfml/imgui-SFML.s

# target to generate assembly for a file
imgui-sfml/imgui-SFML.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui-SFML.cpp.s
.PHONY : imgui-sfml/imgui-SFML.cpp.s

imgui-sfml/imgui.o: imgui-sfml/imgui.cpp.o

.PHONY : imgui-sfml/imgui.o

# target to build an object file
imgui-sfml/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui.cpp.o
.PHONY : imgui-sfml/imgui.cpp.o

imgui-sfml/imgui.i: imgui-sfml/imgui.cpp.i

.PHONY : imgui-sfml/imgui.i

# target to preprocess a source file
imgui-sfml/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui.cpp.i
.PHONY : imgui-sfml/imgui.cpp.i

imgui-sfml/imgui.s: imgui-sfml/imgui.cpp.s

.PHONY : imgui-sfml/imgui.s

# target to generate assembly for a file
imgui-sfml/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui.cpp.s
.PHONY : imgui-sfml/imgui.cpp.s

imgui-sfml/imgui_draw.o: imgui-sfml/imgui_draw.cpp.o

.PHONY : imgui-sfml/imgui_draw.o

# target to build an object file
imgui-sfml/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui_draw.cpp.o
.PHONY : imgui-sfml/imgui_draw.cpp.o

imgui-sfml/imgui_draw.i: imgui-sfml/imgui_draw.cpp.i

.PHONY : imgui-sfml/imgui_draw.i

# target to preprocess a source file
imgui-sfml/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui_draw.cpp.i
.PHONY : imgui-sfml/imgui_draw.cpp.i

imgui-sfml/imgui_draw.s: imgui-sfml/imgui_draw.cpp.s

.PHONY : imgui-sfml/imgui_draw.s

# target to generate assembly for a file
imgui-sfml/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui_draw.cpp.s
.PHONY : imgui-sfml/imgui_draw.cpp.s

imgui-sfml/imgui_widgets.o: imgui-sfml/imgui_widgets.cpp.o

.PHONY : imgui-sfml/imgui_widgets.o

# target to build an object file
imgui-sfml/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui_widgets.cpp.o
.PHONY : imgui-sfml/imgui_widgets.cpp.o

imgui-sfml/imgui_widgets.i: imgui-sfml/imgui_widgets.cpp.i

.PHONY : imgui-sfml/imgui_widgets.i

# target to preprocess a source file
imgui-sfml/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui_widgets.cpp.i
.PHONY : imgui-sfml/imgui_widgets.cpp.i

imgui-sfml/imgui_widgets.s: imgui-sfml/imgui_widgets.cpp.s

.PHONY : imgui-sfml/imgui_widgets.s

# target to generate assembly for a file
imgui-sfml/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/nibbler.dir/build.make CMakeFiles/nibbler.dir/imgui-sfml/imgui_widgets.cpp.s
.PHONY : imgui-sfml/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... nibbler"
	@echo "... class/KNU/World.o"
	@echo "... class/KNU/World.i"
	@echo "... class/KNU/World.s"
	@echo "... class/KNU/component/Component.o"
	@echo "... class/KNU/component/Component.i"
	@echo "... class/KNU/component/Component.s"
	@echo "... class/KNU/entities/Entity.o"
	@echo "... class/KNU/entities/Entity.i"
	@echo "... class/KNU/entities/Entity.s"
	@echo "... class/KNU/events/EventManager.o"
	@echo "... class/KNU/events/EventManager.i"
	@echo "... class/KNU/events/EventManager.s"
	@echo "... class/KNU/systems/System.o"
	@echo "... class/KNU/systems/System.i"
	@echo "... class/KNU/systems/System.s"
	@echo "... class/KNU/utils/Signature.o"
	@echo "... class/KNU/utils/Signature.i"
	@echo "... class/KNU/utils/Signature.s"
	@echo "... class/Univers.o"
	@echo "... class/Univers.i"
	@echo "... class/Univers.s"
	@echo "... class/component/CollisionComponent.o"
	@echo "... class/component/CollisionComponent.i"
	@echo "... class/component/CollisionComponent.s"
	@echo "... class/component/FollowComponent.o"
	@echo "... class/component/FollowComponent.i"
	@echo "... class/component/FollowComponent.s"
	@echo "... class/component/JoystickComponent.o"
	@echo "... class/component/JoystickComponent.i"
	@echo "... class/component/JoystickComponent.s"
	@echo "... class/component/MotionComponent.o"
	@echo "... class/component/MotionComponent.i"
	@echo "... class/component/MotionComponent.s"
	@echo "... class/component/PositionComponent.o"
	@echo "... class/component/PositionComponent.i"
	@echo "... class/component/PositionComponent.s"
	@echo "... class/component/SpriteComponent.o"
	@echo "... class/component/SpriteComponent.i"
	@echo "... class/component/SpriteComponent.s"
	@echo "... class/cores/main.o"
	@echo "... class/cores/main.i"
	@echo "... class/cores/main.s"
	@echo "... class/events/FoodEvent.o"
	@echo "... class/events/FoodEvent.i"
	@echo "... class/events/FoodEvent.s"
	@echo "... class/events/JoystickEvent.o"
	@echo "... class/events/JoystickEvent.i"
	@echo "... class/events/JoystickEvent.s"
	@echo "... class/factory/Factory.o"
	@echo "... class/factory/Factory.i"
	@echo "... class/factory/Factory.s"
	@echo "... class/gui/Core.o"
	@echo "... class/gui/Core.i"
	@echo "... class/gui/Core.s"
	@echo "... class/gui/imgui_demo.o"
	@echo "... class/gui/imgui_demo.i"
	@echo "... class/gui/imgui_demo.s"
	@echo "... class/gui/widget/AWidget.o"
	@echo "... class/gui/widget/AWidget.i"
	@echo "... class/gui/widget/AWidget.s"
	@echo "... class/gui/widget/WidgetChat.o"
	@echo "... class/gui/widget/WidgetChat.i"
	@echo "... class/gui/widget/WidgetChat.s"
	@echo "... class/gui/widget/WidgetExit.o"
	@echo "... class/gui/widget/WidgetExit.i"
	@echo "... class/gui/widget/WidgetExit.s"
	@echo "... class/gui/widget/WidgetLobby.o"
	@echo "... class/gui/widget/WidgetLobby.i"
	@echo "... class/gui/widget/WidgetLobby.s"
	@echo "... class/gui/widget/WidgetSnake.o"
	@echo "... class/gui/widget/WidgetSnake.i"
	@echo "... class/gui/widget/WidgetSnake.s"
	@echo "... class/logger/display/logger_debug.o"
	@echo "... class/logger/display/logger_debug.i"
	@echo "... class/logger/display/logger_debug.s"
	@echo "... class/logger/display/logger_error.o"
	@echo "... class/logger/display/logger_error.i"
	@echo "... class/logger/display/logger_error.s"
	@echo "... class/logger/display/logger_fatal.o"
	@echo "... class/logger/display/logger_fatal.i"
	@echo "... class/logger/display/logger_fatal.s"
	@echo "... class/logger/display/logger_info.o"
	@echo "... class/logger/display/logger_info.i"
	@echo "... class/logger/display/logger_info.s"
	@echo "... class/logger/display/logger_success.o"
	@echo "... class/logger/display/logger_success.i"
	@echo "... class/logger/display/logger_success.s"
	@echo "... class/logger/display/logger_trace.o"
	@echo "... class/logger/display/logger_trace.i"
	@echo "... class/logger/display/logger_trace.s"
	@echo "... class/logger/display/logger_warn.o"
	@echo "... class/logger/display/logger_warn.i"
	@echo "... class/logger/display/logger_warn.s"
	@echo "... class/logger/logger/logger_init.o"
	@echo "... class/logger/logger/logger_init.i"
	@echo "... class/logger/logger/logger_init.s"
	@echo "... class/logger/utils/logger_get_time.o"
	@echo "... class/logger/utils/logger_get_time.i"
	@echo "... class/logger/utils/logger_get_time.s"
	@echo "... class/logger/utils/logger_init_open_file.o"
	@echo "... class/logger/utils/logger_init_open_file.i"
	@echo "... class/logger/utils/logger_init_open_file.s"
	@echo "... class/network/ClientTCP.o"
	@echo "... class/network/ClientTCP.i"
	@echo "... class/network/ClientTCP.s"
	@echo "... class/network/Network.o"
	@echo "... class/network/Network.i"
	@echo "... class/network/Network.s"
	@echo "... class/network/ServerTCP.o"
	@echo "... class/network/ServerTCP.i"
	@echo "... class/network/ServerTCP.s"
	@echo "... class/network/UtilsTCP.o"
	@echo "... class/network/UtilsTCP.i"
	@echo "... class/network/UtilsTCP.s"
	@echo "... class/systems/CollisionSystem.o"
	@echo "... class/systems/CollisionSystem.i"
	@echo "... class/systems/CollisionSystem.s"
	@echo "... class/systems/FollowSystem.o"
	@echo "... class/systems/FollowSystem.i"
	@echo "... class/systems/FollowSystem.s"
	@echo "... class/systems/FoodSystem.o"
	@echo "... class/systems/FoodSystem.i"
	@echo "... class/systems/FoodSystem.s"
	@echo "... class/systems/JoystickSystem.o"
	@echo "... class/systems/JoystickSystem.i"
	@echo "... class/systems/JoystickSystem.s"
	@echo "... class/systems/MotionSystem.o"
	@echo "... class/systems/MotionSystem.i"
	@echo "... class/systems/MotionSystem.s"
	@echo "... class/systems/RenderSystem.o"
	@echo "... class/systems/RenderSystem.i"
	@echo "... class/systems/RenderSystem.s"
	@echo "... imgui-sfml/imgui-SFML.o"
	@echo "... imgui-sfml/imgui-SFML.i"
	@echo "... imgui-sfml/imgui-SFML.s"
	@echo "... imgui-sfml/imgui.o"
	@echo "... imgui-sfml/imgui.i"
	@echo "... imgui-sfml/imgui.s"
	@echo "... imgui-sfml/imgui_draw.o"
	@echo "... imgui-sfml/imgui_draw.i"
	@echo "... imgui-sfml/imgui_draw.s"
	@echo "... imgui-sfml/imgui_widgets.o"
	@echo "... imgui-sfml/imgui_widgets.i"
	@echo "... imgui-sfml/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

